###
POST http://localhost:5000/sign-up HTTP/1.1
Content-Type: application/json

{
    "email": "tienvn998@gmail.com",
    "password": "123",
    "confirmPassword": "123"
}

###
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "email": "tien@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/test-cookie HTTP/1.1